### PR TITLE
Automap: Add support for the discovery state of OBJ models to be saved and loaded

### LINKED ISSUE #1995: Replacement OBJ models invisible on dungeon map after loading save
**Describe the bug**
While modding DFU, I noticed that every model I created was invisible on the explored dungeon map after loading a save and only became visible again after I walked to those invisible models and re-explored the area. However, these re-explored models would disappear again after loading any saves after that as well. 

Recently, I discovered that this only happens if the replacement models are OBJs. As a test, I replaced a staircase model that I was using an OBJ model for with an FBX model and loaded it into my mod. After loading the save, the staircases using that model were now visible on the dungeon's map. 

So there is something about the way DFU is deciding what dungeon pieces to reveal on the map while loading a save that breaks if the piece uses an OBJ model. I'm wondering if this is a similar issue to one Petchema fixed in his pull request #1988. That this part of DFU was only designed to look at the root of the prefab and not at it's children? I've attached a save and the two staircase models to help reproduce this:
[Save.zip](https://github.com/Interkarma/daggerfall-unity/files/5824089/Save.zip)
[Models.zip](https://github.com/Interkarma/daggerfall-unity/files/5824090/Models.zip)

**To Reproduce**
1. Load the OBJ model into your game however you prefer. Make sure you rename the OBJ prefab to "61018.prefab".
2. Load the save game. Notice how the staircases in the corridor in my screenshot is not visible on the dungeon map even though that corridor was explored.
3. Load the FBX model into your game however you prefer.
4. Load the save game. Notice that the staircase pieces are now visible on the map. Please note that if you notice that the model doesn't become transparent, Petchema has already submitted a pull request that fixes this so don't worry.

**Screenshots**
Here are some screenshots of what I am talking about. Please don't worry about these models being completely white. It is a separate issue that I've already reported elsewhere.
This first one is where I'm only using OBJ replacement models. The corridor across the middle of the picture is supposed to be fully explored but pieces of it are missing.
OBJ hidden corridor pieces without FBX test

This second one shows what happened after I replaced the staircase model in that corridor with an FBX model. You can see that now the staircase pieces of that corridor are visible after loading my save.
OBJ hidden corridor pieces with FBX test

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Version: 0.11.0

### PR DESCRIPTION
**Pull request by XJDHDR**
This does two things:
1. Makes the UpdateMeshRendererDungeonState() function be called on all components of all children of the current transform model instead of only the first component in it's root. This fixes an issue where already discovered models on the dungeon map are not revealed after loading a save game if an OBJ file has been used to replace the model.
2. Solves an issue where the SaveStateAutomapDungeon function doesn't properly save the discovery state of OBJ models because it only checked the MeshRenderer component attached to the model's root and not those attached to children.

This PR is identical to #2002, just with all of my changes moved to a new branch. This PR fixes #1995.

### CODE REVIEW

File: Assets/Scripts/Game/Automap.cs [hunk 1]
```diff
@@ -2481,10 +2485,13 @@ private void RestoreStateAutomapDungeon(bool forceNotVisitedInThisRun = false)
...
 
-                        MeshRenderer meshRenderer = currentTransformModel.GetComponent<MeshRenderer>();
-                        if (meshRenderer)
+                        MeshRenderer[] meshRenderers = currentTransformModel.GetComponentsInChildren<MeshRenderer>();
+                        for (int i = 0; i < meshRenderers.Length; i++)
                         {
-                            UpdateMeshRendererDungeonState(ref meshRenderer, automapDungeonState, indexBlock, indexElement, indexModel, forceNotVisitedInThisRun);
+                            if (meshRenderers[i])
+                            {
+                                UpdateMeshRendererDungeonState(meshRenderers[i], automapDungeonState, indexBlock, indexElement, indexModel, forceNotVisitedInThisRun);
```
Comment (Interkarma) [inline Assets/Scripts/Game/Automap.cs:2493]: This is just missing a "ref" for meshRenderers[i] when passed to UpdateMeshRendererState(). Otherwise no issues found, so I'll just merge and add the missing ref on my end.

Comment (XJDHDR) [reply Assets/Scripts/Game/Automap.cs:2493]: I removed it because @rossipaolo [mentoned](https://github.com/Interkarma/daggerfall-unity/pull/2002#discussion_r563820584) that it's not needed.

Comment (Interkarma) [reply Assets/Scripts/Game/Automap.cs:2493]: Well code doesn't compile without it. To remove it, we also need to change the corresponding ref in method signature for UpdateMeshRendererDungeonState().

But yeah @rossipaolo is correct - MeshRenderer is a class, so shouldn't be any issues with removing ref from both call and method. I'm happy to test and change on my side now merged.
